#!/usr/bin/env python3
"""Scores memory lines and writes the numbers back into the files.

By default the clock runs on opportunities to apply: the age of an event is
how many sessions of the project have passed since. A rare line is not
punished — it sets its own rhythm. Scale and step come from config.json.

Events: hit held, use took part in a decision, miss did not hold,
inverse the opposite happened.
S — maturity as a candidate rule, R — urgency of verification.
The script counts, not the agent: otherwise the numbers get nudged.
No dependencies beyond the standard library.
"""

import json
import math
import re
from pathlib import Path

import morf

# ===== Settings =====

MEMORY = morf.memory()
SESSIONS = MEMORY / "sessions.md"
CONFIG_FILE = Path(__file__).with_name("config.json")

# Defaults. The working values live in config.json next to the script:
# weights and formulas share an origin, so they belong together. The canvas
# shows that same file as a link node, so no copy of the values exists.
DEFAULTS = {
    "weight_miss": 1.0,     # the prediction did not hold: absence, weak
    "weight_flip": 2.0,     # the opposite happened: observable, twice as strong
    "min_events": 3,        # below this a line is immature, no discount
    "unit": "sessions",     # what the horizon is measured in: sessions | days
    "levels": ["L0", "L1", "L2", "L3"],
    "horizon_base": 1,      # horizon of the first level
    "horizon_step": 5,      # how much the next horizon grows
    "limits": [40, 30, 25, 20],
}

# Every counter is optional: the skill tells a writer to omit zeros, and a
# line written that way used to match nothing — the run then reported "0
# rescored", which is also what a correct run reports when there is nothing
# to do. The writer below still emits hit and use in full, so generated
# lines and hand-written ones both parse.
LINE_RE = re.compile(
    r"^(?P<head>- (?:↑ )?)"
    # The space sits between the parts, not inside them: a counter that ate its
    # own trailing space left the score block with nothing to match against,
    # and the block then landed in the text and was doubled on the next run.
    #
    # The block is anchored on `S=` rather than on any bracket, because a rule
    # or an observation may legitimately begin with one — `[WIP] …`, or a
    # `[[link]]` — and an unanchored group swallows it silently.
    r"(?:hit:(?P<hit>\d+))? ?(?:use:(?P<use>\d+))? ?"
    r"(?:miss:(?P<miss>\d+))? ?(?:inverse:(?P<inverse>\d+))? ?"
    r"(?:\[S=[^\]]*\])?"
    r"(?P<text>.+?)"
    r"\((?P<sources>s:[^)]*)\)\s*$"
)
SOURCE_RE = re.compile(r"s:(\d{6}-\w+)")
ROW_RE = re.compile(r"^\|\s*s:(?P<id>[\w-]+)\s*\|[^|]*\|\s*(?P<project>[^|]*?)\s*\|")


# ===== Settings =====

def load_config() -> dict:
    """Reads config.json next to the script; on any breakage falls back to defaults."""
    try:
        return {**DEFAULTS, **json.loads(CONFIG_FILE.read_text(encoding="utf-8"))}
    except (OSError, ValueError):
        print(f"{CONFIG_FILE.name} not read, using defaults.")
        return dict(DEFAULTS)


CONFIG = load_config()
LEVELS_FILE = MEMORY / "levels.md"


def horizons() -> list[int]:
    """Horizon of each level: base multiplied by step to the power of its index."""
    base, step = CONFIG["horizon_base"], CONFIG["horizon_step"]
    return [round(base * step ** i) for i in range(len(CONFIG["levels"]))]


def publish_levels() -> None:
    """Publishes the levels for the agent: it never reads config.json."""
    sessions = CONFIG["unit"] == "sessions"
    unit = "sessions of the project" if sessions else "days"
    tick = "sessions" if sessions else "days"
    rows = ["# Levels", "",
            "Generated by `score-memory.py` from `Scripts/config.json`. Never edit by hand.",
            "Consolidate top down: fill the upper level from the one below it first.",
            f"Horizon is measured in {unit}. Base {CONFIG['horizon_base']}, "
            f"step ×{CONFIG['horizon_step']}.", "",
            "| Level | Horizon | Line limit | Consolidated after |",
            "|---|---|---|---|"]
    limits = CONFIG["limits"]
    for i, (name, h) in enumerate(zip(CONFIG["levels"], horizons())):
        limit = limits[i] if i < len(limits) else limits[-1]
        due = "every session" if i == 0 else f"{horizons()[i - 1]} {tick}"
        rows.append(f"| `{name}.md` | {h} | {limit} | {due} |")
    LEVELS_FILE.write_text("\n".join(rows) + "\n", encoding="utf-8")


# ===== Opportunities to apply =====

def exposure_scale(project: str) -> dict[str, int]:
    """Sessions of the project in order: id to index. This is the time scale."""
    if not SESSIONS.exists():
        return {}
    scale, position = {}, 0
    for line in SESSIONS.read_text(encoding="utf-8").splitlines():
        row = ROW_RE.match(line)
        if row and row.group("project") == project:
            scale[row.group("id")] = position
            position += 1
    return scale


def ages(sources: str, scale: dict[str, int]) -> list[int]:
    """Age of every event in opportunities, freshest first."""
    if not scale:
        return []
    now = max(scale.values())
    found = [scale[m] for m in SOURCE_RE.findall(sources) if m in scale]
    return sorted(now - position for position in found)


# ===== Decay by overdue =====

def alive(count: int, event_ages: list[int]) -> float:
    """Effective weight: the event count discounted by overdue against rhythm.

    A line's rhythm is its own average gap. The overdue s shows how many
    times it is late against that rhythm; at s <= 1 there is no discount.
    """
    if count <= 0 or len(event_ages) < CONFIG["min_events"]:
        return float(count)
    newest, oldest = event_ages[0], event_ages[len(event_ages) - 1]
    rhythm = oldest / len(event_ages)
    if rhythm <= 0 or newest <= rhythm:
        return float(count)
    return count * rhythm / newest


def tempo(event_ages: list[int]) -> float:
    """Direction: rate over the last two events against the last five."""
    def rate(depth: int) -> float:
        if len(event_ages) < depth or event_ages[depth - 1] <= 0:
            return 0.0
        return depth / event_ages[depth - 1]

    near, far = rate(2), rate(5)
    return round(near / far, 2) if far else 0.0


# ===== Scores =====

def scores(hit: float, use: float, miss: float, inverse: float) -> tuple[float, float]:
    """S is maturity (addends, not factors), R is urgency of verification."""
    evidence = hit - CONFIG["weight_miss"] * miss - CONFIG["weight_flip"] * inverse
    confidence = max(0.0, 1.0 - 2.0 ** (-evidence)) if evidence > 0 else 0.0
    return round(confidence + math.log1p(use), 2), round(use * (1.0 - confidence), 2)


# ===== Processing a file =====

def rewrite_line(line: str, scale: dict[str, int]) -> str:
    """Recomputes the scores and writes them in, touching nothing else."""
    match = LINE_RE.match(line)
    if not match:
        return line

    event_ages = ages(match.group("sources"), scale)
    keys = ("hit", "use", "miss", "inverse")
    counts = {key: int(match.group(key) or 0) for key in keys}
    weights = {key: alive(value, event_ages) for key, value in counts.items()}

    retention, urgency = scores(*(weights[key] for key in keys))
    marks = " ".join(f"{key}:{counts[key]}" for key in keys if counts[key] or key in ("hit", "use"))
    return (
        f"{match.group('head')}{marks} [S={retention} R={urgency} t={tempo(event_ages)}] "
        f"{match.group('text').lstrip()}({match.group('sources')})"
    )


def process(path: Path) -> int:
    """Returns how many lines were rescored in one level file.

    A file whose numbers did not move is left untouched. Writing it back
    regardless changed nothing a reader could see and everything a watcher
    could: it churned the store's history and moved the modification time,
    which another script had taken for a record of a decision.
    """
    if path.stem not in CONFIG["levels"][1:]:   # the first level is the inbox, it is not scored
        return 0
    scale = exposure_scale(path.parent.name)
    lines = path.read_text(encoding="utf-8").splitlines()
    rewritten = [rewrite_line(line, scale) for line in lines]
    changed = sum(1 for a, b in zip(lines, rewritten) if a != b)
    if changed:
        path.write_text("\n".join(rewritten) + "\n", encoding="utf-8")
    return changed


# ===== Entry point =====

def main() -> None:
    publish_levels()
    total = sum(process(path) for path in sorted(MEMORY.rglob("*.md")))
    print(f"Lines rescored: {total}. Horizons: {', '.join(map(str, horizons()))}.")


if __name__ == "__main__":
    main()
